name: atmos_database
description: Library for atmos create database tables and use it by Atom735
version: 0.16.0+1
homepage: https://github.com/Atom735/atmos_database

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  atmos_binary_buffer: ^0.16.5
  meta: ^1.7.0
  sqlite3: ^1.6.0

dev_dependencies:
  atmos_lints: ^0.16.1
  test: ^1.20.2
